# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_update_email_length'),
        ('django_oscar_fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fee ID')),
                ('fee_name', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Fee name')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount')),
                ('message', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='order.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Fee',
                'verbose_name_plural': 'Order Fees',
            },
        ),
        migrations.RemoveField(
            model_name='fee',
            name='max_affected_items',
        ),
        migrations.AlterField(
            model_name='fee',
            name='type',
            field=models.CharField(blank=True, choices=[('Percentage', "Fee is a percentage of the basket's value"), ('Absolute', 'Fee is a fixed amount')], max_length=128, verbose_name='Type'),
        ),
    ]
